// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LoginTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginTest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1274, height: 692 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.css(".inputWrapper:nth-child(1) > input")).click()
    await driver.findElement(By.css(".inputWrapper:nth-child(1) > input")).sendKeys("Admin")
    await driver.findElement(By.css(".inputWrapper:nth-child(2) > input")).sendKeys("1234")
    await driver.findElement(By.linkText("Login")).click()
  })
})
