// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RegisterNotEmail', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RegisterNotEmail', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 884, height: 692 })
    await driver.findElement(By.linkText("Sign Up")).click()
    await driver.findElement(By.css(".optionCard:nth-child(2) > a")).click()
    await driver.findElement(By.name("nationalId")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("fasdfasdfasdf")
    await driver.findElement(By.css(".next-button")).click()
  })
})
